version: "3.9"

services:
  backend:
    build: .
    container_name: lumber-backend
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    build: .
    container_name: lumber-frontend
    command: >
      streamlit run dashboard/app.py
      --server.port=8501
      --server.address=0.0.0.0
    environment:
      API_URL: http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
